### ISSUE TITLE
Console output on Windows

### ISSUE THREAD

**Issue by Fox32** [google/test_runner.dart#17]
The new "one line status while finding test suites" is problematic on Windows. It produces the following output:
```
Found 0 test suites (0 Standalone VM, 0 Dartium)...
←[2A
Found 1 test suites (1 Standalone VM, 0 Dartium)...
←[2A
Found 2 test suites (2 Standalone VM, 0 Dartium)...
←[2A
Found 3 test suites (3 Standalone VM, 0 Dartium)...
←[2A
Found 4 test suites (4 Standalone VM, 0 Dartium)...
←[2A
Found 5 test suites (5 Standalone VM, 0 Dartium)...
←[2A
Found 6 test suites (6 Standalone VM, 0 Dartium)...
←[2A
Found 7 test suites (7 Standalone VM, 0 Dartium)...
←[2A
Found 8 test suites (8 Standalone VM, 0 Dartium)...
```
Either we have to detect if Windows is used (Platform.isWindows) or we only enabled it for the colored output. I think pub also has such a feature while it is resolving depdencies, it is deactivated on Windows.
As an alternative one could also append a dot for every suite found, and only print the summary after all files were searched.

I also get the following output while running tests:
```
Detailed results of test suite storage_profile_storage_test.dart:
ÔöîÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔö
ÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔ
öÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
Ôöé No tests found.
````
Not sure why I get these scrambled characters, I think it worked in the past.

**Comment by nicolasgarnier** [comment]
Ah damit I forgot that Windows did not support ANSI escape codes. I will also render `-c` useless in case of Windows...

Just pushed a new version that uses dots to show progress in windows. And that also avoid using any ANSI escape characters in windows.

Can you try it?

Not sure about the scrambled output of the test content... I haven't really touched this in a while. Let me have a look...

**Comment by Fox32** [comment]
```
Looking for test suites........................Found 20 test suites (20 Standalo
ne VM, 0 Dartium).
```
I think there is a line break missing. During a short look at the code I also saw this line: https://github.com/google/test_runner.dart/blob/master/bin/run_tests.dart#L173

**Comment by nicolasgarnier** [comment]
Just pushed a new version. Should be OK now. Can you try again please?

**Comment by nicolasgarnier** [comment]
For the scrambled output it looks like the characters that windows cant display are:

┌───────────
 |

**Comment by nicolasgarnier** [comment]
Very strange....

**Comment by nicolasgarnier** [comment]
Can you try running `chcp 65001` before starting the test runner just in case that fixes it?

**Comment by nicolasgarnier** [comment]
It looks like these box drawing characters should be supported in DOS: http://en.wikipedia.org/wiki/Box-drawing_character#DOS

Oh well.... I've pushed a new version that uses `.`, `-` and `|` instead. Can you try it out and let me know if it displays better please?

**Comment by Fox32** [comment]
Using ```chcp 65001``` doesn't help, but the box characters are fine in the new version.

However the line break is still missing, or is that by design?
```
Looking for test suites........................Found 20 test suites (20 Standalo
ne VM, 0 Dartium).
```

**Comment by nicolasgarnier** [comment]
OK thanks. I'll have a look. Nope it should be there :) I thought it was a missing \r but that didn't help...

**Comment by nicolasgarnier** [comment]
Could you try again v0.2.11+9 please? :)

**Comment by Fox32** [comment]
Your commit looks fine, but somehow it still doesn't break?
I try to debug it later today.

**Comment by nicolasgarnier** [comment]
maybe with `\r\n\r` instead fo `\r\n`? (that's still 1 line break on Linux) :D

**Comment by Fox32** [comment]
I'm busy till next week, but the. I will look at it. Something is not right
there...

Am Freitag, 16. Januar 2015 schrieb Nicolas Garnier :

> maybe with \r\n\r instead fo \r\n? (that's still 1 line break on Linux) :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/test_runner.dart/issues/17#issuecomment-70255419>
> .
>


-- 
Mit freundlichen Grüßen
Oliver Sand

**Comment by Fox32** [comment]
I finally had time to look at this problem. I committed a fix as https://github.com/Fox32/test_runner.dart/commit/817aeee19b89ee6d4b65547d4d13f573aebe3021

But I think that the general problem here was that I'm using a Dart version were ```stdout``` is async, while you are already using the version were it is sync again. Therefore mixing ```print``` (which is sync) and ```stdout``` calls results in the wrong order.

Should I submit that as a PR?

**Comment by nicolasgarnier** [comment]
Ah yes that must be it (sync vs async stdout). I've included your code in the latest change version of the test runner. Thx for your help!
